[advisories]
# 使用系统 git，规避托管平台对 HTTP Smart Protocol 的限制。
git-fetch-with-cli = true
unmaintained = "all"
yanked = "warn"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "allow"

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Unicode-3.0",
  "Zlib",
]
exceptions = [
  { name = "ring", allow = ["ISC", "OpenSSL", "BSD-3-Clause"] },
]
confidence-threshold = 0.8

[licenses.private]
ignore = false
registries = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
