[package]
name = "spark-transport"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
bench = false

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
