
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.anstyle]]
version = "1.0.13"
criteria = "safe-to-run"

[[exemptions.anyhow]]
version = "1.0.100"
criteria = "safe-to-run"

[[exemptions.arc-swap]]
version = "1.7.1"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.89"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-rs]]
version = "1.14.1"
criteria = "safe-to-deploy"

[[exemptions.aws-lc-sys]]
version = "0.32.3"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-run"

[[exemptions.bindgen]]
version = "0.72.1"
criteria = "safe-to-deploy"

[[exemptions.bit-set]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.bit-vec]]
version = "0.8.0"
criteria = "safe-to-run"

[[exemptions.bitflags]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.19.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.cast]]
version = "0.3.0"
criteria = "safe-to-run"

[[exemptions.cc]]
version = "1.2.43"
criteria = "safe-to-deploy"

[[exemptions.cesu8]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.cexpr]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.cfg_aliases]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.cfg_aliases]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-run"

[[exemptions.clang-sys]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.clap]]
version = "4.5.50"
criteria = "safe-to-run"

[[exemptions.clap_builder]]
version = "4.5.50"
criteria = "safe-to-run"

[[exemptions.clap_lex]]
version = "0.7.6"
criteria = "safe-to-run"

[[exemptions.cmake]]
version = "0.1.54"
criteria = "safe-to-deploy"

[[exemptions.combine]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-channel]]
version = "0.5.15"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-run"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.deranged]]
version = "0.5.5"
criteria = "safe-to-run"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dunce]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.either]]
version = "1.15.0"
criteria = "safe-to-deploy"

[[exemptions.equivalent]]
version = "1.0.2"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.14"
criteria = "safe-to-run"

[[exemptions.fastbloom]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-run"

[[exemptions.find-msvc-tools]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.fnv]]
version = "1.0.7"
criteria = "safe-to-run"

[[exemptions.fs_extra]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-executor]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-io]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generator]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.9"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.glob]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.7.1"
criteria = "safe-to-run"

[[exemptions.hashbrown]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.hex]]
version = "0.4.3"
criteria = "safe-to-run"

[[exemptions.indexmap]]
version = "2.12.0"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.17"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.10.5"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.13.0"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.jni]]
version = "0.21.1"
criteria = "safe-to-deploy"

[[exemptions.jni-sys]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.jobserver]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.82"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.177"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.8.9"
criteria = "safe-to-deploy"

[[exemptions.libm]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.11.0"
criteria = "safe-to-run"

[[exemptions.lock_api]]
version = "0.4.14"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.28"
criteria = "safe-to-deploy"

[[exemptions.loom]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.lru-slab]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.matchers]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.6"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.28.0"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "7.1.3"
criteria = "safe-to-deploy"

[[exemptions.nu-ansi-term]]
version = "0.50.3"
criteria = "safe-to-deploy"

[[exemptions.num-conv]]
version = "0.1.0"
criteria = "safe-to-run"

[[exemptions.num-traits]]
version = "0.2.19"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.openssl-probe]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry]]
version = "0.22.0"
criteria = "safe-to-deploy"

[[exemptions.opentelemetry_sdk]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.ordered-float]]
version = "4.6.0"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.5"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.12"
criteria = "safe-to-deploy"

[[exemptions.pem]]
version = "3.0.6"
criteria = "safe-to-run"

[[exemptions.percent-encoding]]
version = "2.3.2"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.powerfmt]]
version = "0.2.0"
criteria = "safe-to-run"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.prettyplease]]
version = "0.2.37"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.103"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.9.0"
criteria = "safe-to-run"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-run"

[[exemptions.quinn]]
version = "0.11.9"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.11.13"
criteria = "safe-to-deploy"

[[exemptions.quinn-udp]]
version = "0.5.14"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.41"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.rand_xorshift]]
version = "0.4.0"
criteria = "safe-to-run"

[[exemptions.rayon]]
version = "1.11.0"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.13.0"
criteria = "safe-to-run"

[[exemptions.rcgen]]
version = "0.13.2"
criteria = "safe-to-run"

[[exemptions.redox_syscall]]
version = "0.5.18"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.12.2"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.8"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.14"
criteria = "safe-to-deploy"

[[exemptions.rustc-hash]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.1.2"
criteria = "safe-to-run"

[[exemptions.rustls]]
version = "0.23.34"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.13.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-platform-verifier]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.rustls-platform-verifier-android]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.103.8"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.22"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.1"
criteria = "safe-to-run"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.same-file]]
version = "1.0.6"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.28"
criteria = "safe-to-deploy"

[[exemptions.scoped-tls]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "3.5.1"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.15.0"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.145"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.9"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.9"
criteria = "safe-to-deploy"

[[exemptions.sharded-slab]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.11"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.15.1"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.108"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.23.0"
criteria = "safe-to-run"

[[exemptions.thiserror]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.17"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.17"
criteria = "safe-to-deploy"

[[exemptions.thread_local]]
version = "1.1.9"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.44"
criteria = "safe-to-run"

[[exemptions.time-core]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.tinytemplate]]
version = "1.2.1"
criteria = "safe-to-run"

[[exemptions.tinyvec]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.48.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-macros]]
version = "2.6.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-rustls]]
version = "0.26.4"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.8.23"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.11"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.22.27"
criteria = "safe-to-deploy"

[[exemptions.toml_write]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.41"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.30"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.34"
criteria = "safe-to-deploy"

[[exemptions.tracing-log]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-opentelemetry]]
version = "0.23.0"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.20"
criteria = "safe-to-deploy"

[[exemptions.tracing-test]]
version = "0.2.5"
criteria = "safe-to-run"

[[exemptions.tracing-test-macro]]
version = "0.2.5"
criteria = "safe-to-run"

[[exemptions.typenum]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-run"

[[exemptions.unicode-ident]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.urlencoding]]
version = "2.1.3"
criteria = "safe-to-deploy"

[[exemptions.valuable]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wait-timeout]]
version = "0.2.1"
criteria = "safe-to-run"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasip2]]
version = "1.0.1+wasi-0.2.4"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.105"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.82"
criteria = "safe-to-run"

[[exemptions.web-time]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-root-certs]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.winapi-util]]
version = "0.1.11"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.61.3"
criteria = "safe-to-deploy"

[[exemptions.windows-collections]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-future]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-implement]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows-interface]]
version = "0.59.3"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.windows-link]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.windows-numerics]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.windows-result]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.windows-strings]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.45.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.60.2"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.61.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.53.5"
criteria = "safe-to-deploy"

[[exemptions.windows-threading]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.42.2"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.53.1"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen]]
version = "0.46.0"
criteria = "safe-to-deploy"

[[exemptions.yasna]]
version = "0.5.2"
criteria = "safe-to-run"

[[exemptions.zerocopy]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.27"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.2"
criteria = "safe-to-deploy"
