[package]
name = "spark-codec-sdp"
version = "0.1.0"
rust-version = "1.89"
edition.workspace = true
authors = ["Gemini 架构组 <architecture@gemini.example>"]
license = "Apache-2.0"
description = "Session Description Protocol codec scaffolding for spark-core"
publish = false

[lib]
bench = false

[features]
default = ["std"]
alloc = ["spark-codecs/alloc"]
std = ["alloc", "spark-codecs/std"]
compat_v0 = ["spark-codecs/compat_v0"]

[dependencies]
spark-codecs = { workspace = true, default-features = false }
spark-core = { workspace = true, default-features = false }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
