[package]
name = "spark-codecs"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Shared codec contracts and utilities for spark protocol implementations"

[lib]
bench = false

[features]
default = ["std"]
alloc = ["spark-core/alloc"]
std = ["alloc", "spark-core/std"]
compat_v0 = ["spark-core/compat_v0"]

[dependencies]
spark-core = { path = "../../spark-core", default-features = false }

[package.metadata.docs.rs]
all-features = true
