[package]
name = "spark-transport-udp"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"

[lib]
# UDP 传输仅包含测试代码。禁用 `cargo bench` 回调，避免 `--quick`
# 参数触发 `libtest` 错误。
bench = false

[dependencies]
spark-core = { path = "../../spark-core" }
spark-transport = { path = "../../spark-transport" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "io-util", "sync"], optional = true }

[features]
default = ["runtime-tokio"]
runtime-tokio = ["dep:tokio"]
batch-udp-unix = ["runtime-tokio", "dep:socket2", "dep:nix"]

[dependencies.socket2]
workspace = true
optional = true

[target.'cfg(target_os = "linux")'.dependencies.nix]
version = "0.28"
optional = true
default-features = false
features = ["socket", "net", "uio"]
