# RFC 索引表（由 CI 守门检查）
#
# 书写规范：
# [[rfc]]
# number = 4122
# sections = ["§4.1", "§4.2"]
#
# - `number`：RFC 编号，使用十进制整数表示。
# - `sections`：该 RFC 在 doc 注释中被引用的章节列表，保留 "§" 前缀以便于检索。
#
# 若当前版本尚未引用任何 RFC，可保持文件仅包含此注释。
