[package]
name = "spark-transport-tls"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
# TLS 传输同样暂无基准测试目标，为避免 `cargo bench -- --quick` 传递
# 非法参数至 `libtest`，直接关闭基准运行。
bench = false

[dependencies]
spark-core = { path = "../../spark-core" }
spark-transport-tcp = { path = "../spark-transport-tcp" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "io-util"] }
rustls = { workspace = true, default-features = false, features = ["std"] }
tokio-rustls = { workspace = true }
arc-swap = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
batch-udp-unix = ["socket2"]

[dependencies.socket2]
workspace = true
optional = true
