[package]
name = "spark-impl-tck"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[dependencies]
spark-core = { path = "../../spark-core" }

[dev-dependencies]
spark-transport-tcp = { path = "../spark-transport-tcp" }
spark-transport-udp = { path = "../spark-transport-udp" }
spark-transport-tls = { path = "../spark-transport-tls" }
spark-transport-quic = { path = "../spark-transport-quic" }
