[package]
name = "spark-impl-tck"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
# `cargo bench -- --quick` 会向所有基于 `libtest` 的单元测试传递额外参数，
# `spark-impl-tck` 不提供基准测试入口，因此禁用基准运行以避免参数解析失败。
bench = false

[dependencies]
spark-core = { path = "../../spark-core" }

[dev-dependencies]
spark-transport-tcp = { path = "../spark-transport-tcp" }
spark-transport-udp = { path = "../spark-transport-udp" }
spark-transport-tls = { path = "../spark-transport-tls" }
spark-transport-quic = { path = "../spark-transport-quic" }
