[package]
name = "spark-transport-tcp"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
# TCP 传输 crate 以单元测试验证协议行为，禁用基准运行以避免 `--quick`
# 交给 `libtest` 造成参数解析失败。
bench = false

[dependencies]
spark-core = { path = "../../spark-core" }
thiserror = "1.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "io-util"] }

[features]
default = []
# TCP 半关闭实现依赖 socket2；保留 batch-udp-unix 特性以便复用该依赖。
batch-udp-unix = []

[dependencies.socket2]
version = "0.6"
