name: Minimal CI Guardrails

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  minimal-ci:
    name: fmt + clippy + build + test + cargo-deny + doc-density
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache cargo artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: minimal-ci
          cache-on-failure: true

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.16.4

      - name: Format check
        run: cargo fmt --all --check

      - name: Clippy lint
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Build workspace
        run: cargo build --workspace

      - name: Run tests
        run: cargo test --workspace

      - name: Check documentation density
        run: python3 tools/check_doc_density.py --threshold 0.06

      - name: Cargo deny audit
        run: cargo deny check bans licenses advisories sources
